/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.border.Border;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import static telas.conexao.con;
/**
 *
 * @author Anchieta
 */
public class tela_inicio extends javax.swing.JFrame {
    private final String codiguin;

    /**
     * Creates new form NewJFrame
     */
    public tela_inicio() {
        
        initComponents();
        codiguin = gerarCodigo();
        URL url = this.getClass().getResource("hostexpress.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        conexao.Conectar();
        jLabel7.setVisible(false);
    }
    public static String gerarCodigo() {
        Random random = new Random();
        StringBuilder codigo = new StringBuilder();
        
        for (int i = 0; i < 6; i++) {
            codigo.append(random.nextInt(10));
        }
        return codigo.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfemail = new javax.swing.JTextField();
        pfsenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btcadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btentrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HostExpress");
        setForeground(new java.awt.Color(204, 102, 255));
        setLocation(new java.awt.Point(500, 500));

        tfemail.setText("2100830m@escolas.anchieta.br");

        pfsenha.setText("123");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel6.setText("esqueci minha senha");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        btcadastrar.setBackground(new java.awt.Color(51, 51, 255));
        btcadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btcadastrar.setText("Cadastrar");
        btcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Login");

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setText("E-mail:");

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setText("Senha:");

        jLabel5.setText("Ainda não tem uma conta?");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/circulo.png"))); // NOI18N
        jLabel7.setText("Email ou senha incorretos! Tente novamente ou clique em 'esqueci a senha'");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/logo.png"))); // NOI18N

        btentrar.setBackground(new java.awt.Color(51, 51, 255));
        btentrar.setForeground(new java.awt.Color(255, 255, 255));
        btentrar.setText("Entrar");
        btentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btentrarActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(pfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(btcadastrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btentrar)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(tfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(pfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastrarActionPerformed
        // TODO add your handling code here:
        tela_cadastrar tela_cadastro = new tela_cadastrar();
        tela_cadastro.setVisible(true);
    }//GEN-LAST:event_btcadastrarActionPerformed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        Font originalFont = new Font("Arial", Font.PLAIN, 10);
        Font underlineFont = originalFont.deriveFont(Font.PLAIN);
        jLabel6.setFont(underlineFont.deriveFont(Font.PLAIN));
        jLabel6.setText("<html><u>esqueci minha senha</u></html>");
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        Font originalFont = new Font("Arial", Font.PLAIN, 10);
        jLabel6.setFont(originalFont.deriveFont(Font.PLAIN, 10));
        jLabel6.setText("esqueci minha senha");
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        String sql;
        conexao.email = tfemail.getText();
        if (tfemail.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "Insira seu e-mail e então clique em 'esqueci a senha'.");
        }
        else if (tfemail.getText().contains("@") || tfemail.getText().endsWith(".com") || tfemail.getText().endsWith(".br")){
            try {
                sql = "SELECT * FROM empresas WHERE email LIKE ?";
                PreparedStatement stm = con.prepareStatement(sql,ResultSet.TYPE_SCROLL_SENSITIVE, 
                ResultSet.CONCUR_UPDATABLE);
                stm.setString(1,conexao.email);
                ResultSet rs = stm.executeQuery();
                if (rs.first()){
                    String host = "smtp.gmail.com";
                    String port = "587";
                    String email2 = "hostexpressjundiai@gmail.com";
                    String email_senha = "kwvs ukak jgel gjvi";
                    String destinatario = conexao.email;
                    String assunto = "Troca de Senha";
                    String corpo = "Olá, digite este código no nosso aplicativo para redefinir sua senha: \n" + codiguin;

                    Properties propiedades = new Properties();                  
                    propiedades.put("mail.smtp.ssl.trust", host);
                    propiedades.put("mail.smtp.auth", "true");
                    propiedades.put("mail.smtp.starttls.enable", "true");
                    propiedades.put("mail.smtp.host", host);
                    propiedades.put("mail.smtp.port", port);
                    
                    
                    Session secao = Session.getInstance(propiedades, new Authenticator(){
                    @Override
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(email2, email_senha);
                    }
                });
                try{
                    Message mensagem = new MimeMessage(secao);
                    mensagem.setFrom(new InternetAddress(email2));
                    mensagem.setRecipients(Message.RecipientType.TO, InternetAddress.parse(destinatario));
                    mensagem.setSubject(assunto);
                    mensagem.setText(corpo);

                    Transport.send(mensagem);
                    System.out.println("E-mail enviado com sucesso!");
                    tela_senha telinha_senha = new tela_senha(codiguin);
                    telinha_senha.setVisible(true); 
                }
                catch (MessagingException e){
                    JOptionPane.showMessageDialog(null, "E-mail inválido!");
                    System.out.println("oi " + e);
                }
            }
            else{
               JOptionPane.showMessageDialog(null,"Este e-mail não está cadastrado!");
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Erro no login! + e");
        }    
        }
        else {
            JOptionPane.showMessageDialog(null,"Insira um e-mail válido.");
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btentrarActionPerformed
        // TODO add your handling code here:
        Border borda;
        borda = BorderFactory.createLineBorder(Color.white,2);
        pfsenha.setBorder(borda);
        jLabel7.setVisible(false);
        String sql, email, senha;
        email =tfemail.getText();
        senha = pfsenha.getText();
        if(email.isBlank() || senha.isBlank()){
            JOptionPane.showMessageDialog(null,"Preencha todos os campos!");
        }
        else{
            try {
                sql = "SELECT * FROM empresas WHERE email = ? AND senha = ?";
                PreparedStatement stm = con.prepareStatement(sql,ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
                stm.setString(1,email);
                stm.setString(2,senha);
                ResultSet rs = stm.executeQuery();
                if (rs.first()){
                    tela_menu telinha_menu = new tela_menu();
                    telinha_menu.setExtendedState(MAXIMIZED_BOTH);
                    telinha_menu.setVisible(true);
                    this.dispose();
                }
                else{
                    borda = BorderFactory.createLineBorder(Color.red,2);
                    pfsenha.setBorder(borda);
                    pfsenha.requestFocus();
                    pfsenha.setText("");
                    jLabel7.setVisible(true);

                }
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Erro no login!" + e);
            }
        }
    }//GEN-LAST:event_btentrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
           

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tela_inicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcadastrar;
    private javax.swing.JButton btentrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField pfsenha;
    private javax.swing.JTextField tfemail;
    // End of variables declaration//GEN-END:variables
}
