/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import com.sun.tools.javac.Main;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.*;
import javax.swing.*;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.border.Border;
import static telas.conexao.con;

/**
 *
 * @author Anchieta
 */
public class tela_senha extends javax.swing.JFrame {
        
    /**
     * Creates new form tela_senha
     * @param codiguin
    
     */
    public tela_senha(String codiguin) {
        initComponents();
        URL url = this.getClass().getResource("hostexpress.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        btsalvar.setVisible(false);
        lblsenha.setVisible(false);
        lblnovasenha.setVisible(false);
        pfsenha.setVisible(false);
        pfnovasenha.setVisible(false);
        jLabel7.setVisible(false);
        jToggleButton1.setVisible(false);
        jToggleButton2.setVisible(false);
        tfcodigo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume(); 
                }
            }
        });
        tfcodigo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                Border borda;
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    jLabel7.setVisible(false);
                    String senha = tfcodigo.getText();
                    borda = BorderFactory.createLineBorder(Color.white,1);
                    tfcodigo.setBorder(borda);
                    if(senha.contentEquals(codiguin)){
                        lbltitulo.setText("Crie sua nova senha");
                        tfcodigo.setVisible(false);
                        btsalvar.setVisible(true);
                        lblsenha.setVisible(true);
                        lblnovasenha.setVisible(true);
                        pfsenha.setVisible(true);
                        pfnovasenha.setVisible(true);
                        jToggleButton1.setVisible(true);
                        jToggleButton2.setVisible(true);
                    }
                    else{
                       borda = BorderFactory.createLineBorder(Color.red,2);
                       tfcodigo.setBorder(borda);
                       jLabel7.setText("O código está incorreto!");
                       jLabel7.setVisible(true);
                    }
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        lblsenha = new javax.swing.JLabel();
        lblnovasenha = new javax.swing.JLabel();
        tfcodigo = new javax.swing.JTextField();
        btsalvar = new javax.swing.JButton();
        pfsenha = new javax.swing.JPasswordField();
        pfnovasenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar nova senha");
        setLocation(new java.awt.Point(600, 400));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setName("Cadastar nova senha"); // NOI18N
        setResizable(false);

        lbltitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbltitulo.setText("Digite o código que foi enviado ao seu e-mail:");
        lbltitulo.setToolTipText("");
        lbltitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblsenha.setText("Nova senha:");

        lblnovasenha.setText("Confirmar senha:");

        tfcodigo.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        tfcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodigoActionPerformed(evt);
            }
        });

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/circulo.png"))); // NOI18N
        jLabel7.setText("Código incorreto! Tente novamente");

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/hidden.png"))); // NOI18N
        jToggleButton1.setMaximumSize(new java.awt.Dimension(15, 23));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(15, 23));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/hidden.png"))); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pfnovasenha, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblnovasenha)
                    .addComponent(lblsenha)
                    .addComponent(pfsenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btsalvar)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(121, 121, 121))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(174, Short.MAX_VALUE)
                    .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(161, 161, 161)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbltitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(8, 8, 8)
                .addComponent(lblsenha)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblnovasenha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pfnovasenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(116, 116, 116)
                    .addComponent(tfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(97, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigoActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
        Border borda;
        borda = BorderFactory.createLineBorder(Color.white,2);
        pfsenha.setBorder(borda);
        if (pfsenha.getText().contentEquals(pfnovasenha.getText())){
            int rs;
            String sql,senha;
            senha = pfsenha.getText();
            try {
                sql = "update empresas set senha = ? where email = ?";
               // System.out.println(sql);
                PreparedStatement stm = con.prepareStatement(sql);
                stm.setString(1, senha);
                stm.setString(2, conexao.email);
                rs = stm.executeUpdate();
                if (rs>0) {
                    JOptionPane.showMessageDialog(null, "Dados Gravados com Sucesso!");
                } 
                else {
                    JOptionPane.showMessageDialog(null, "Erro ao Gravar!");
                }
            } 
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro! "+ e);
            }
        }
        else{
            borda = BorderFactory.createLineBorder(Color.red,2);
            pfsenha.setBorder(borda);
            pfsenha.requestFocus();
            pfsenha.setText("");
            jLabel7.setText("As senhas não correspondem!");
            jLabel7.setVisible(true);
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (pfsenha.getEchoChar() == (char)0) {
            pfsenha.setEchoChar('*');
            URL iconurl = Main.class.getResource("/src/eye.png");
            ImageIcon icon = new ImageIcon(iconurl);
            jToggleButton1.setIcon(icon);
                } 
        else {
            pfsenha.setEchoChar((char)0);
            URL iconurl = Main.class.getResource("/src/hidden.png");
            ImageIcon icon = new ImageIcon(iconurl);
            jToggleButton1.setIcon(icon);                
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if (pfnovasenha.getEchoChar() == (char)0) {
            pfnovasenha.setEchoChar('*');
            URL iconurl = Main.class.getResource("/src/eye.png");
            ImageIcon icon = new ImageIcon(iconurl);
            jToggleButton2.setIcon(icon);
                } 
        else {
            pfnovasenha.setEchoChar((char)0);
            URL iconurl = Main.class.getResource("/src/hidden.png");
            ImageIcon icon = new ImageIcon(iconurl);
            jToggleButton2.setIcon(icon);  
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
    
            public void run(String codiguin) {
                new tela_senha(codiguin).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btsalvar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblnovasenha;
    private javax.swing.JLabel lblsenha;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPasswordField pfnovasenha;
    private javax.swing.JPasswordField pfsenha;
    private javax.swing.JTextField tfcodigo;
    // End of variables declaration//GEN-END:variables
}
