/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import com.sun.tools.javac.Main;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Random;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import static telas.conexao.con;


public class tela_cadastrar extends javax.swing.JFrame {
    /**
     * Creates new form tela_cadastrar
     */
    public String email;
    public String codiguin = gerarCodigo();
    public tela_cadastrar() {
        initComponents();
        conexao.Conectar();
        tfcodigo.setVisible(false);
        jLabel4.setVisible(false);
        jPasswordField1.setVisible(false);
        jPasswordField2.setVisible(false);
        jButton1.setVisible(false);
        jToggleButton1.setVisible(false);
        jToggleButton2.setVisible(false);
        jLabel7.setVisible(false);
        URL url = this.getClass().getResource("hostexpress.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        
        tfcodigo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume(); 
                }
            }
        });
        
        tfcodigo.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                Border borda;
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    String senha = tfcodigo.getText();
                    borda = BorderFactory.createLineBorder(Color.white,1);
                    tfcodigo.setBorder(borda);
                    if(senha.contentEquals(codiguin)){
                        jLabel3.setText("Crie sua senha");
                        tfcodigo.setVisible(false);
                        jButton1.setVisible(true);
                        jToggleButton1.setVisible(true);
                        jToggleButton2.setVisible(true);
                        jPasswordField1.setVisible(true);
                        jPasswordField2.setVisible(true);                        
                    }
                    else{
                       borda = BorderFactory.createLineBorder(Color.red,2);
                       tfcodigo.setBorder(borda);
                       tfcodigo.setText("");
                       jLabel3.setText("O código está incorreto!");
                       jLabel7.setVisible(true);
                    }
                }
            }
        });
    }
    public static String gerarCodigo() {
        Random random = new Random();
        StringBuilder codigo = new StringBuilder();
        
        for (int i = 0; i < 6; i++) {
            codigo.append(random.nextInt(10));
        }
        return codigo.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        btproximo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        tfcodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar");
        setLocation(new java.awt.Point(640, 300));
        setMinimumSize(new java.awt.Dimension(450, 280));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 280));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("E-mail:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 90, 60, 15);
        getContentPane().add(tfemail);
        tfemail.setBounds(110, 112, 250, 22);
        tfemail.getAccessibleContext().setAccessibleName("");

        btproximo.setText("Próximo");
        btproximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btproximoActionPerformed(evt);
            }
        });
        getContentPane().add(btproximo);
        btproximo.setBounds(190, 150, 90, 40);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE EMPRESAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 0, 240, 21);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/circulo.png"))); // NOI18N
        jLabel7.setText("As senhas não correspondem!");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 40, 170, 16);

        jLabel3.setText("Insira seu e-mail para confirmação");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 60, 200, 17);

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Confirme a senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 140, 120, 15);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/hidden.png"))); // NOI18N
        jToggleButton1.setMaximumSize(new java.awt.Dimension(15, 23));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(15, 23));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(370, 160, 22, 22);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/hidden.png"))); // NOI18N
        jToggleButton2.setMaximumSize(new java.awt.Dimension(15, 23));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(15, 23));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(370, 110, 22, 22);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 200, 72, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(110, 160, 250, 23);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(110, 110, 250, 23);

        tfcodigo.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        tfcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodigoActionPerformed(evt);
            }
        });
        getContentPane().add(tfcodigo);
        tfcodigo.setBounds(190, 100, 90, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btproximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btproximoActionPerformed
        // TODO add your handling code here:
        Border borda;
        borda = BorderFactory.createLineBorder(Color.red,2);
        String sql;

        btproximo.addActionListener((ActionEvent e) -> {
            email = tfemail.getText();
        });
        
        email = tfemail.getText();
        
        if(email.contains("@") || email.contains(".com") || email.contains(".br")){
            try{
                sql = "SELECT email FROM HE_EMPRESAS WHERE email LIKE ?";
                PreparedStatement stm = con.prepareStatement(sql,ResultSet.TYPE_SCROLL_SENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
                stm.setString(1,email);
                ResultSet rs = stm.executeQuery();
                if (!rs.first()){
                        String host = "smtp.gmail.com";
                        String port = "587";
                        String email2 = "hostexpressjundiai@gmail.com";
                        String email_senha = "kwvs ukak jgel gjvi";
                        String destinatario = email;
                        String assunto = "Log-in";
                        String corpo = "Olá, digite este código no nosso aplicativo para continuar seu cadastro: \n" + codiguin;

                        Properties propiedades = new Properties();                  
                        propiedades.put("mail.smtp.ssl.trust", host);
                        propiedades.put("mail.smtp.auth", "true");
                        propiedades.put("mail.smtp.starttls.enable", "true");
                        propiedades.put("mail.smtp.host", host);
                        propiedades.put("mail.smtp.port", port);


                        Session secao = Session.getInstance(propiedades, new Authenticator(){
                            @Override
                            protected PasswordAuthentication getPasswordAuthentication() {
                                return new PasswordAuthentication(email2, email_senha);
                            }
                        });
                    try{
                        Message mensagem = new MimeMessage(secao);
                        mensagem.setFrom(new InternetAddress(email2));
                        mensagem.setRecipients(Message.RecipientType.TO, InternetAddress.parse(destinatario));
                        mensagem.setSubject(assunto);
                        mensagem.setText(corpo);

                        Transport.send(mensagem);
                        System.out.println("E-mail enviado com sucesso!");
                    }
                    catch(MessagingException e){
                        System.out.println("oi" + e);
                    }
                    btproximo.setVisible(false);
                    tfcodigo.setVisible(true);
                    tfemail.setVisible(false);
                    jLabel2.setVisible(false);
                    jLabel3.setText("Insira o código de verificação enviado para seu E-mail:");
                    jLabel3.setSize(210, 16);
                }
                else{
                    tfemail.setText("");
                    tfemail.setBorder(borda);
                    tfemail.requestFocus();
                    JOptionPane.showMessageDialog(null,"Este E-mail já está cadastrado!");
                }
            }
            catch(SQLException e){
                System.out.println(e);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Insira um E-mail válido!");
        }
    }//GEN-LAST:event_btproximoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jPasswordField1.getEchoChar() == (char)0) {
            jPasswordField1.setEchoChar('*');
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("../src/eye.png"));
            jToggleButton1.setIcon((Icon) icon.getImage());
        }
        else {
            jPasswordField1.setEchoChar((char)0);
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("../src/hidden.png"));
            jToggleButton1.setIcon((Icon) icon.getImage());
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if (jPasswordField2.getEchoChar() == (char)0) {
            jPasswordField2.setEchoChar('*');
            URL iconurl = Main.class.getResource("./src/eye.png");
            ImageIcon icon = new ImageIcon(iconurl);
            jToggleButton2.setIcon(icon);
                } 
        else {
            jPasswordField2.setEchoChar((char)0);
            URL iconurl = Main.class.getResource("./src/hidden.png");
            ImageIcon icon = new ImageIcon(iconurl);
            jToggleButton2.setIcon(icon);  
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Border borda;
        borda = BorderFactory.createLineBorder(Color.white,2);
        jPasswordField1.setBorder(borda);
        if (jPasswordField1.getText().contentEquals(jPasswordField2.getText())){
            int rs;
            String sql,senha;
            senha = jPasswordField1.getText();
            try {
                sql = "insert into he_empresas (email,senha) values(?,?)";
                PreparedStatement stm = con.prepareStatement(sql);
                stm.setString(1, email);
                stm.setString(2,String.valueOf(senha.hashCode()));
                rs = stm.executeUpdate();
                if (rs>0) {
                    tela_empresa telinha_empresa = new tela_empresa(email);
                    telinha_empresa.setVisible(true);
                    this.dispose();
                } 
                else {
                    JOptionPane.showMessageDialog(null, "Erro ao Gravar!");
                }
            } 
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro! "+ e);
            }
        }
        else{
            borda = BorderFactory.createLineBorder(Color.red,2);
            jPasswordField1.setBorder(borda);
            jPasswordField1.requestFocus();
            jPasswordField1.setText("");
            jLabel7.setText("As senhas não correspondem!");
            jLabel7.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tela_cadastrar().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btproximo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField tfcodigo;
    private javax.swing.JTextField tfemail;
    // End of variables declaration//GEN-END:variables
}